# Generated by Django 4.1.2 on 2022-11-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("club_number", models.IntegerField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("pass_number", models.IntegerField(primary_key=True, serialize=False)),
                ("player_name", models.CharField(max_length=50)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scorerSheet.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("game_number", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=50)),
                (
                    "guest_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_team",
                        to="scorerSheet.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_team",
                        to="scorerSheet.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "game_number")},
            },
        ),
    ]
