# Generated by Django 4.1.3 on 2022-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="game_moves",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
