# Generated by Django 4.1.5 on 2023-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cell",
            old_name="game_moves",
            new_name="game_move_1_2",
        ),
        migrations.AddField(
            model_name="cell",
            name="game_move_2_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cell",
            name="game_move_3_H",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cell",
            name="game_move_H_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
