# Generated by Django 4.1.5 on 2023-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0002_rename_game_moves_cell_game_move_1_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="game_move_1_2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cell",
            name="game_move_2_3",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cell",
            name="game_move_3_H",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cell",
            name="game_move_H_1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
