# Generated by Django 4.1.5 on 2023-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scorerSheet",
            "0003_alter_cell_game_move_1_2_alter_cell_game_move_2_3_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lineup",
            name="jersey_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
