# Generated by Django 4.1.3 on 2022-11-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0004_alter_battingorder_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="battingorder",
            name="game",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="scorerSheet.game",
            ),
            preserve_default=False,
        ),
    ]
