# Generated by Django 4.1.5 on 2023-02-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0004_inningssummation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inningssummation",
            name="player",
        ),
        migrations.AddField(
            model_name="inningssummation",
            name="team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="scorerSheet.team",
            ),
            preserve_default=False,
        ),
    ]
