# Generated by Django 4.1.5 on 2023-02-15 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0005_remove_inningssummation_player_inningssummation_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inningssummation",
            name="errors",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="hits",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="left_on_base",
            field=models.SmallIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="runs",
            field=models.SmallIntegerField(null=True),
        ),
    ]
