# Generated by Django 4.1.5 on 2023-02-15 13:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0006_alter_inningssummation_errors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inningssummation",
            name="errors",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="hits",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="inning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scorerSheet.inning",
            ),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="left_on_base",
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="inningssummation",
            name="runs",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
