# Generated by Django 4.1.2 on 2022-12-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0006_rename_position_battingorder_defensive_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scorerSheet.battingorder",
            ),
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
