# Generated by Django 4.1.3 on 2022-12-12 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0007_alter_cell_score_delete_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=None,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
            preserve_default=False,
        ),
    ]
