# Generated by Django 4.1.2 on 2022-12-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0007_alter_cell_score_delete_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battingorder",
            name="enter_inning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enter_inning",
                to="scorerSheet.inning",
            ),
        ),
    ]
