# Generated by Django 4.1.5 on 2023-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0004_lineup_jersey_number"),
        ("scorerSheet", "0007_alter_inningssummation_errors_and_more"),
    ]

    operations = []
