# Generated by Django 4.1.2 on 2022-12-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0008_alter_battingorder_enter_inning"),
        ("scorerSheet", "0008_cell_position"),
    ]

    operations = []
