# Generated by Django 5.0.3 on 2024-03-13 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scorerSheet", "0008_merge_20230216_1528"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeOfChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inning_in",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "inning_part",
                    models.CharField(
                        default="T",
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator(regex="[TBtb]")
                        ],
                    ),
                ),
                (
                    "batsperson",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="lineup",
            name="enter_inning",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enter_inning",
                to="scorerSheet.timeofchange",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="exit_inning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_inning",
                to="scorerSheet.timeofchange",
            ),
        ),
    ]
