# Generated by Django 4.1.2 on 2022-12-13 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0009_merge_20221212_1839"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defensive_position",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                (
                    "enter_inning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enter_inning",
                        to="scorerSheet.inning",
                    ),
                ),
                (
                    "exit_inning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_inning",
                        to="scorerSheet.inning",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scorerSheet.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scorerSheet.player",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cell",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scorerSheet.lineup"
            ),
        ),
        migrations.DeleteModel(
            name="BattingOrder",
        ),
    ]
