# Generated by Django 5.0.3 on 2024-03-19 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scorerSheet", "0009_timeofchange_alter_lineup_enter_inning_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineup",
            name="defensive_position",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="enter_inning",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="exit_inning",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="jersey_number",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="player",
        ),
        migrations.AddField(
            model_name="lineup",
            name="batting_pos",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.CreateModel(
            name="PlayerRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jersey_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "defensive_position",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ]
                    ),
                ),
                (
                    "enter_inning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enter_inning",
                        to="scorerSheet.timeofchange",
                    ),
                ),
                (
                    "line_up_pos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scorerSheet.lineup",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scorerSheet.player",
                    ),
                ),
            ],
        ),
    ]
