# Generated by Django 4.1.3 on 2022-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorerSheet", "0010_lineup_alter_cell_score_delete_battingorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="club_number",
            field=models.IntegerField(unique=True),
        ),
    ]
