# Generated by Django 5.0.3 on 2024-03-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scorerSheet", "0010_remove_lineup_defensive_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineup",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scorerSheet.team",
            ),
        ),
    ]
